baseurl = "https://rbspy.github.io/"
title = "rbspy"
languageCode = "en-us"
theme = "crisp"
[params]
  logo = "https://rbspy.github.io/rbspy.jpg"
[[menu.main]]
    name = "Home"
    weight = -120
    url = "/"
[[menu.main]]
    name = "Installing"
    weight = -110
    url = "/installing/"
[[menu.main]]
    name = "Using rbspy"
    weight = -100
    url = "/using-rbspy/"
[[menu.main]]
    name = "rbspy vs stackprof"
    weight = -90
    url = "/rbspy-vs-stackprof/"
[[menu.main]]
    name = "Getting help"
    weight = -80
    url = "/getting-help/"
[[menu.main]]
    pre= "<i class='fa fa-github fa-1x'></i> "
    name = "GitHub"
    weight = -70
    url = "https://github.com/rbspy/rbspy"
[[menu.profiling]]
    name = "About the guide"
    weight = -130
    url = "/about-profiling-guide/"
[[menu.profiling]]
    name = "Questions to ask when optimizing"
    weight = -120
    url = "/optimization-questions/"
[[menu.profiling]]
    name = "Benchmarking your code"
    weight = -110
    url = "/benchmarking-your-code/"
[[menu.profiling]]
    name = "Using flamegraphs"
    weight = -100
    url = "/using-flamegraphs/"
